interface Resources {
  "apie-mus": {
    "section1_body_description": "Įmonė <strong>UAB Kompservisas</strong> specializuojasi naudotų verslo klasės kompiuterių prekybos bei aptarnavimo sferoje. Verslą pradėjome dar 2000ias metais pavadinimu \"Kibirnetas\". <strong>{{value}} metai patirties</strong> rinkoje leidžia mums užtikrinti teikiamų paslaugų kokybę, bei garantuoti parduodamos elektronikos našumą ir ilgaamžiškumą.",
    "section1_title_about_US": "Apie mus",
    "section2_body_description": "Esame atviri bendradarbiavimo pasiūlymams. Galime tiekti kompiuterinę techniką jūsų ofisui, viešajai įstaigai ar municipaliniam objektui. Visą parduodamą techniką tikriname patys. Suteikiame garantiją, išrašome sąskaitas faktūras, parduodame techniką lizingu. Susisiekite su mumis nuspaudę mygtuką \"Susisiekti\" arba paskambinę šiais telefono numeriais: <strong>+370 699 69578</strong>, <strong>+370 699 62246.</strong>",
    "section2_title_cooperation": "Bendradarbiavimas"
  },
  "common": {
    "color_mode_switch_to_dark": "Tamsus režimas",
    "color_mode_switch_to_light": "Šviesus režimas",
    "disclaimer_desktops": "Įsigykite aukštos kokybės naudotus stacionarius kompiuterius iš Kompserviso. Mūsų siūlomi stacionarūs kompiuteriai yra idealus pasirinkimas tiek verslui, tiek kasdieniam naudojimui. Kiekvienas kompiuteris yra kruopščiai patikrinamas ir paruošiamas naudojimui. Užtikriname puikią kainos ir kokybės santykį, suteikiame garantiją.",
    "disclaimer_laptops": "Mūsų asortimente rasite platų kokybiškų, profesionaliai patikrintų nešiojamųjų kompiuterių pasirinkimą, idealiai tinkantį verslo ir asmeninėms reikmėms. Kiekvienas įrenginys yra atidžiai paruoštas ir patikrintas, užtikrinant geriausią naudojimo patirtį.",
    "filters": "Filtrai",
    "filters_manufacturer": "Gamintojas",
    "filters_processor": "Procesorius",
    "filters_product_type": "Prekės tipas",
    "filters_screen_size": "Ekrano dydis",
    "filters_ssd_size": "SSD talpa",
    "footer_link_about_us": "Apie mus",
    "footer_link_about_us_path": "/apie-mus",
    "footer_link_co-operation": "Bendradarbiavimas",
    "footer_link_co-operation_path": "/apie-mus",
    "footer_text_all_rights_reserved": "© {{year}} UAB Kompservisas. Visos teisės išsaugotos.",
    "footer_text_general_information": "Bendra informacija",
    "footer_text_kompiuteriu_remontas": "Kompiuterių remontas Vilniuje",
    "footer_text_moto": "<strong>KOMPSERVISAS</strong> - jūsų patikimas naudotų verslo klasės kompiuterių pardavimo ir remonto partneris.",
    "footer_text_services": "Paslaugos",
    "footer_text_used_computers": "Naudoti kompiuteriai Vilniuje",
    "footer_text_used_desktops": "Stacionarūs naudoti kompiuteriai Vilniuje",
    "footer_text_used_laptops": "Nešiojami naudoti kompiuteriai (laptop) Vilniuje",
    "header_call_us": "Skambinkite ir klauskite:",
    "header_link_apie_mus": "Apie mus",
    "header_link_apie_mus_path": "/apie-mus",
    "header_link_kitos_prekes": "Kitos prekės",
    "header_link_kitos_prekes_path": "/kitos-prekes",
    "header_link_kontaktai": "Kontaktai",
    "header_link_kontaktai_path": "/kontaktai",
    "header_link_monitoriai": "Monitoriai",
    "header_link_monitoriai_path": "/monitoriai",
    "header_link_nesiojami": "Nešiojami",
    "header_link_nesiojami_path": "/nesiojami",
    "header_link_pagrindinis_path": "/",
    "header_link_pagrindins": "Pagrindinis",
    "header_link_remontas": "Remontas",
    "header_link_remontas_path": "/remontas",
    "header_link_stacionarus": "Stacionarūs",
    "header_link_stacionarus_path": "/stacionarus",
    "header_link_supirkimas": "Supirkimas",
    "header_link_supirkimas_path": "/supirkimas",
    "quantity": "vnt",
    "quantity_one": "{{count}} vnt",
    "quantity_other": "{{count}} vnt",
    "quantity_sold_out": "Išparduota",
    "add_to_cart": "Į KREPŠELĮ",
    "shop_will_be_closed": "Parduotuvė bus uždaryta nuo {{startDate}} iki {{endDate}} dėl profilaktinių darbų. Atsiprašome už nepatogumus.",
    "sorting": "Rūšiavimas",
    "sorting_price_asc": "nuo pigiausio",
    "sorting_price_desc": "nuo brangiausio"
  },
  "kontaktai": {
    "section1_address": "Adresas: {{value}}",
    "section1_contacts": "Kontaktai: Tel. <strong><1>+370 699 69578</1></strong>, <strong><3>+370 699 62246</3></strong>",
    "section1_title_UAB_Kompservisas": "UAB Kompservisas",
    "section1_working_hours": "Darbo laikas: {{value}}",
    "section2_bank_account": "A/s Nr. <strong>LT82 7300 0101 2925 3214</strong>",
    "section2_company_code": "Įmonės kodas: <strong>125675394</strong>",
    "section2_title_company_details": "Rekvizitai",
    "section2_vat_code": "PVM mokėtojo kodas: <strong>LT256753917</strong>",
    "section3_about_us": "Apie mus: <2>kompservisas.lt/apie-mus</2>",
    "section3_email": "El paštas: <1>info@kompservisas.lt</1>",
    "section3_facebook": "Facebook: <2>facebook.com/kompservisas</2>",
    "section3_title_lets_keep_in_touch": "Bendraukime",
    "section4_our_location": "Mus rasite"
  },
  "meta": {
    "ApieMus": {
      "keywords": "kompiuterių remontas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "UAB Kompservisas - prekyba naudotais verslo klasės kompiuteriais. Kompiuterių remontas. Prekiaujame patikimais, bei patikrintais verlso klasės nešiojamais, bei stacionariais kompiuteriais.",
      "metaName": "Apie Mus | UAB Kompservisas",
      "name": "Apie Mus",
      "path": "/apie-mus"
    },
    "KitosPrekes": {
      "keywords": "kompiuterių aksesuarai, maitinimo blokai, verslo klasė",
      "metaDescription": "Maitinimo blokai, kompiuterių dalys, kompiuterių aksesuarai",
      "metaName": "Kitos prekės | UAB Kompservisas",
      "name": "Kitos prekės",
      "path": "/kitos-prekes"
    },
    "Kontaktai": {
      "keywords": "kompiuterių remontas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "Kontaktai | Tel. +370 699 69578, +370 699 62246. I-V 10.00 - 18.00.",
      "metaName": "Kontaktai | UAB Kompservisas",
      "name": "Kontaktai",
      "path": "/kontaktai"
    },
    "Krepselis": {
      "keywords": "kompiuterių remontas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "Prekių Krepšelis",
      "metaName": "Krepšelis | UAB Kompservisas",
      "name": "Krepšelis",
      "path": "/krepselis"
    },
    "Monitoriai": {
      "keywords": "naudoti kompiuteriai, verslo klasė, naudoti monitoriai",
      "metaDescription": "Naudoti kokybiški monitoriai už prieinamą kainą",
      "metaName": "Monitoriai | UAB Kompservisas",
      "name": "Monitoriai",
      "path": "/monitoriai"
    },
    "Nesiojami": {
      "keywords": "nešiojami kompiuteriai, verslo klasė",
      "metaDescription": "Nešiojami kompiuteriai visoje Lietuvoje už prieinamą kainą.",
      "metaName": "Nešiojami | UAB Kompservisas",
      "name": "Nešiojami",
      "path": "/nesiojami"
    },
    "Pagrindinis": {
      "keywords": "kompiuterių remontas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "UAB Kompservisas - prekyba naudotais verslo klasės kompiuteriais. Kompiuterių remontas. Prekiaujame patikimais, bei patikrintais verlso klasės nešiojamais, bei stacionariais kompiuteriais.",
      "metaName": "UAB Kompservisas | Naudoti kompiuteriai | Algirdo g. 32",
      "name": "Pagrindinis",
      "path": "/"
    },
    "Remontas": {
      "keywords": "kompiuterių remontas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "Rinkitės mus, jei ieškote kokybės ir patirties už prieinamą kainą. Sutaisysime Jūsų naudotą nešiojamą ar stacionarų kompiuterį. Algirdo g. 32 / Šaltinių g. 2, Naujamiestis",
      "metaName": "Kompiuterių remontas Vilniuje - Kompservisas",
      "name": "Remontas",
      "path": "/remontas"
    },
    "Stacionarus": {
      "keywords": "stacionarūs kompiuteriai, verslo klasė",
      "metaDescription": "Stacionarūs kompiuteriai visoje Lietuvoje už prieinamą kainą.",
      "metaName": "Stacionarūs kompiuteriai | UAB Kompservisas",
      "name": "Stacionarūs",
      "path": "/stacionarus"
    },
    "Supirkimas": {
      "keywords": "kompiuterių supirkimas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "Naudotų kompiuterių supirkimas.",
      "metaName": "Supirkimas | UAB Kompservisas",
      "name": "Supirkimas",
      "path": "/supirkimas"
    },
    "Uzsakymas": {
      "keywords": "kompiuterių supirkimas, naudoti kompiuteriai, verslo klasė",
      "metaDescription": "Užsakymo forma",
      "metaName": "Užsakymas | UAB Kompservisas",
      "name": "Užsakymas",
      "path": "DynamicPages.Uzsakymas.path"
    }
  },
  "nesiojami": {
    "section1_product_address_note": "Prekę galite įsigyti adresu <strong>Algirdo g. 32 / Šaltinių g. 2</strong>",
    "section1_product_description_photo_discrepancy": "Ši nuotrauka yra pavyzdinė ir gali neatitikti realios prekės būklės",
    "section1_product_description_price": "Kaina: <strong>{{value}}</strong>",
    "section1_product_description_product_type_A": "<strong>A</strong> - kompiuteris neturi jokių naudojimo žymių arba tos žymės yra labai menkos.",
    "section1_product_description_product_type_B": "<strong>B</strong> - kompiuteris turi smulkių naudojimo žymių (smulkus įbrėžimai).",
    "section1_product_description_product_type_C": "<strong>C</strong> - kompiuteris yra tvarkingas techniškai, tačiau turi stambesnių įbrėžimų ir kitų nusidėvėjimo žimių.",
    "section1_product_description_product_types": "Naudotų kompiuterių rūšys",
    "section1_product_description_qnt": "Kiekis: <strong>{{value}}</strong>",
    "section2_technical_specifications": "Techniniai duomenys"
  },
  "pagrindinis": {
    "call_us": "Teiraukitės:",
    "meta_data_name": "Pagrindinis",
    "meta_data_page_description": "UAB Kompservisas - prekyba naudotais verslo klasės kompiuteriais. Kompiuterių remontas. Prekiaujame patikimais, bei patikrintais verlso klasės nešiojamais, bei stacionariais kompiuteriais.",
    "meta_data_page_meta_name": "UAB Kompservisas | Naudoti kompiuteriai | Algirdo g. 32",
    "section1_body": "Už prieinamą kainą",
    "section1_button": "Pirkti",
    "section1_title": "Verslo klasės naudoti kompiuteriai už prieinamą kainą",
    "section2_catalogue_button_desktops": "Stacionarūs <1>kompiuteriai</1>",
    "section2_catalogue_button_laptops": "Nešiojami <1>kompiuteriai</1>",
    "section2_paragraph_button": "Katalogas",
    "section2_paragraph_reliability": "Parduodame tik patikrintus kokybiškus bei patikimus verslo klasės kompiuterius jūsų darbui bei pramogoms",
    "section3_about_us": "Kompservisas - tai patikimų ir kruopščiai paruoštų naudotų kompiuterių parduotuvė Vilniuje. Siūlome tik kokybiškus, profesionaliai patikrintus ir paruoštus įrenginius darbui ir pramogoms. Taip pat teikiame <1>kompiuterių remonto</1> Vilniuje paslaugas.",
    "section4_catalogue_button_recommended": "Rekomenduojame",
    "section4_preparation": "<strong>Paruošimas</strong>. Kiekvieną kompiuterį prieš parduodant patikriname spec. įranga, atliekamas valymas, atnaujinama programinė įranga. Tokiu būdu užtikriname, kad kiekvienas įrenginys veiktų efektyviai ir būtų patikimas ilgą laiką.",
    "section5_warranty": "<strong>Garantija</strong>. Visiems parduodamiems kompiuteriams suteikiama 1 metų garantija.",
    "section6_business_clients": "<strong>Verslo klientams</strong>. Mūsų pasiūla yra idealus pasirinkimas įmonėms ir organizacijoms, ieškančioms patikimų naudotų kompiuterių didesniais kiekiais. Siūlome konkurencingas kainas ir specialius pasiūlymus verslui, atsižvelgdami į jūsų specifinius poreikius."
  },
  "product": {
    "camera": "Vaizdo kamera",
    "cpu": "Procesorius",
    "description": "Aprašymas",
    "graphics_card": "Vaizdo plokštė",
    "hdd": "Kietojo disko apimtis (HDD)",
    "manufacturer": "Gamintojas",
    "model": "Modelis",
    "name": "Pavadinimas",
    "operating_system": "Operacinė sistema",
    "optical_drive": "Optinis diskas",
    "ram": "Operatyvioji atmintis (RAM)",
    "screen_resolution": "Ekrano raiška",
    "screen_size": "Ekrano įstrižainė (coliais)",
    "ssd": "Kietojo disko apimtis (SSD)",
    "warranty": "Garantija",
    "wifi": "Wi-Fi tinklas"
  },
  "remontas": {
    "Gedimo nustatymas (netaikomas jei atliekamas remontas)": "Gedimo nustatymas (netaikomas jei atliekamas remontas)",
    "Kompiuterio aušinimo sistemos pilnas valymas (kai ardomas visas kompiuteris, keičiama termopasta, išvalomas ir sutepamas aušintuvas)": "Kompiuterio aušinimo sistemos pilnas valymas (kai ardomas visas kompiuteris, keičiama termopasta, išvalomas ir sutepamas aušintuvas)",
    "Kompiuterio aušinimo sistemos valymas (kompiuteris nėra ardomas, yra gamintojo numatytas priėjimas prie aušinimo sistemos)": "Kompiuterio aušinimo sistemos valymas (kompiuteris nėra ardomas, yra gamintojo numatytas priėjimas prie aušinimo sistemos)",
    "Nešiojamo kompiuterio maitinimo adapterio remontas": "Nešiojamo kompiuterio maitinimo adapterio remontas",
    "Nešiojamo kompiuterio maitinimo lizdo keitimo darbai (detalių kaina neįskaičiuota)": "Nešiojamo kompiuterio maitinimo lizdo keitimo darbai (detalių kaina neįskaičiuota)",
    "Nešiojamo kompiuterio remontas (detalių kaina neįskaičiuota)": "Nešiojamo kompiuterio remontas (detalių kaina neįskaičiuota)",
    "Nešiojamo kompiuterio vyrių arba kabelių remontas/keitimas (detalių kaina neįskaičiuota)": "Nešiojamo kompiuterio vyrių arba kabelių remontas/keitimas (detalių kaina neįskaičiuota)",
    "Operacinės sistemos atstatymas/perrašymas (klientas turi pateikti norimų įdiegti programų licencijas)": "Operacinės sistemos atstatymas/perrašymas (klientas turi pateikti norimų įdiegti programų licencijas)",
    "Operacinės sistemos atstatymas/perrašymas su duomenų išsaugojimu (klientas turi pateikti norimų įdiegti programų licencijas)": "Operacinės sistemos atstatymas/perrašymas su duomenų išsaugojimu (klientas turi pateikti norimų įdiegti programų licencijas)",
    "Pirminė apžiūra ir konsultacija": "Pirminė apžiūra ir konsultacija",
    "Stacionaraus kompiuterio pagrindinės plokštės keitimas": "Stacionaraus kompiuterio pagrindinės plokštės keitimas",
    "Stacionaraus kompiuterio vidinio įrenginio diegimas": "Stacionaraus kompiuterio vidinio įrenginio diegimas",
    "Užpilto nešiojamo kompiuterio remontas (detalių kaina neįskaičiuota)": "Užpilto nešiojamo kompiuterio remontas (detalių kaina neįskaičiuota)",
    "Užpilto nešiojamo kompiuterio valymas (be detalių keitimo)": "Užpilto nešiojamo kompiuterio valymas (be detalių keitimo)",
    "static": {
      "section1_intro_body_initial_inspection": "Pirminė sugedusio kompiuterio apžiūra Nemokama!",
      "section1_intro_button_contact_us": "SKAMBINKITE IR KLAUSKITE:",
      "section1_intro_button_prices": "Kainos",
      "section1_intro_title_repairs": "Nešiojamų ir stacionarių kompiuterių remontas Vilniuje",
      "section2_price_list_id": "kainorastis",
      "section2_price_list_info_VAT": "Išrašome PVM sąskaitas-faktūras.",
      "section2_price_list_info_preliminary_prices": "Svarbu! Lentelėje pateikiamos remonto kainos yra preliminarios, galutinė kaina gali ženkliai skirtis nuo žemiau nurodytų.",
      "section2_price_list_price": "Kaina",
      "section2_price_list_repair_description": "Remonto aprašymas",
      "section2_price_list_title_repair_price_list": "Kompiuterio remonto darbų kainoraštis",
      "section3_repair_process": "Kompiuteris paliekamas dirbtuvėje, meistras įsigilina į problemos esmę. Suradus priežastį sudaro preliminarų išlaidų sąrašą ir tik klientui patvirtinus tęsia darbus!",
      "section3_repair_process_handover": "Pinigai iš kliento paimami tik pilnai atlikus remontą, remontui suteikiama garantija.",
      "section3_repair_process_info_initial_inspection": "Pirminė sugedusio kompiuterio apžiūra Nemokama!",
      "section3_repair_process_product_evaluation": "Kad mūsų pagalba jums būtų naudinga ir sumokėti už remontą pinigai duotų jums maksimalią naudą. Mes kartu su klientu turime nuspręsti, ar remonto metu kompiuterį tinkamiausia atstatyti jo originalioje sandaroje arba keičiant dalis - dalinai patobulinti, o gal ir visiškai atnaujinti „morališkai pasenusią“ techniką.",
      "section3_repair_process_title": "Kompiuterio remontas",
      "section3_repair_process_title_general_evaluation": "Pirminė apžiūra",
      "section3_repair_process_title_handover": "Kompiuterio atidavimas",
      "section3_repair_process_title_repair_process": "Kompiuterių remonto procesas",
      "section4_about_us_body": "Jau daugiau nei 20 metų vilniečiams siūlome kokybiškas kompiuterių remonto ir naudotų kompiuterių bei jų komponentų pardavimo paslaugas. Per šį nemažą laikotarpį esame taisę itin sudėtingus kompiuterių komponentų ir programinės įrangos gedimus. Prireikus visuomet pasiūlome alternatyvas. Susisiekite ir padarysime viską, ką galime!",
      "section4_about_us_title": "Apie UAB Kompservisas",
      "section4_reviews": "Kompiuterių remonto atsiliepimai",
      "section4_reviews_AJ": "„Geriausi atsiliepimai apie šios įmonės specialistus. Suprasdami, kad sugedęs kompiuteris man skubiai reikalingas darbui, labai operatyviai 1,5 valandos eigoje užsakė naują detalę, ją atsivežė, sutaisė ir net išvalė kompiuterį, nors dėl valymo nesikreipiau. Ačiū!“",
      "section4_reviews_AusraA": "„Puiki įmonė, viską suprantamai paaiškina, pataria, mandagiai aptarnauja. Pačios geriausios rekomendacijos! Ačiū!“",
      "section4_reviews_Bozena": "„Čia dirbantys meistrai gerai išmano savo darbą. Profesionaliai patikrina,prireikus užsako ir atveža reikalingą detalę. prie kiekvieno kliento prieina su supratimu ir kulturingai aptarnauja. Kai reikia pagalbos, visą laiką iškluso, paaiškina, padeda. Rekomenduoju kreiptis į šią įmonę.“",
      "section4_reviews_DonatasG": "„Užėjau su senuku kompu, įdėjo atminties, rekomendavo ir pakeitė kietąjį diską į SSD, aptarnavimu labai patenkintas.“",
      "section4_reviews_Egidijus": "„Visada gerai paaiškina problemos esmę. Jei reikia, paskatina pasirinkti pigesnį sprendimą. Rekomenduoju!“",
      "section4_reviews_Renata": "„Puikus aptarnavimas, profesionalūs meistrai, greitas darbas. Rekomenduoju!“",
      "section4_reviews_Sarunas": "„Sutvarkė stacionarų kompiuterį greit ir kokybiškai.“",
      "section4_reviews_VytautasP": "„Labai patikimi ir kokybiškai darbą atliekantys meistrai. Prekiauja tikrai gerais kompiuteriais ir suteikia garantinį aptarnavimą. Daug kartų išgelbėjo. Rekomenduoju.“",
      "section5_FAQ": "Dažnai užduodami klausimai apie kompiuterių remontą",
      "section5_body_clean_display": "Tinkamas ekrano valymas yra dar viena svarbi sąlyga, kurią reikia išpildyti, jeigu norite, kad šis įrenginys tarnautų kuo ilgiau, kadangi Jūsų akys yra ne mažiau svarbios nei Jūsų kompiuteris. Atminkite, kad kompiuterio ekranas turi būti valomas šiam tikslui skirtomis servetėlėmis arba specialu valikliu.",
      "section5_body_cleaning": "Dar vienas patarimas, kurio irgi yra verta paisyti, tas, kad būtina valyti ne tik įrenginio klaviatūrą (būtent taip elgiasi didelė dalis vartotojų). Jeigu norite, kad kompiuteris veiktų nepriekaištingai kuo ilgiau, tokiu atveju nepamirškite tinkamai išvalyti ir jungčių bei aušinimo sistemos.",
      "section5_body_power_grid": "Ne ką mažiau svarbu yra ir tai, kaip atliekate įkrovimo procesą. Dėmesį verta atkreipti į tai, kad nemaža nešiojamų kompiuterių savininkų galvoja, kad įrenginys visada gali būti įjungtas į kištukinį lizdą. Belieka tik pridurti, kad toks  jūsų poelgis neturės neigiamos įtakos įrenginio veikimui, tačiau, jeigu norite užtikrinti geriausią rezultatą, tuomet reikėtų elgtis šiek tiek kitaip: kompiuterį įkraukite anksti ryte, o vos tik pastebite, kad baterija jau yra pilnai įkrauta, sustabdykite įkrovimą.",
      "section5_body_ventilated_room": "Kompiuteris turi būti laikomas taip, kad nebūtų užblokuota oro įsiurbimo anga, priešingu atveju, bus slopinamas oro srautas bei pakenkiama kompiuteriui. Pravartu periodiškai kompiuterį išvalyti tiek išorės, tiek ir viduje",
      "section5_closing": "Tikimės, kad šie patarimai padės jums tinkamai prižiūrėti kompiuterį, o taip pat - užtikrins ilgą bei sklandų jo tarnavimą. Na, o jeigu reikalingas kompiuterių remontas Vilniuje, rinkitės KOMPSERVISĄ. Tai - profesionalios kompiuterių remonto paslaugos ir dar daugiau sprendimų.",
      "section5_malware_body": "Vienas sprendimų, kuris jums padės užtikrinti tinkamą šio įrenginio priežiūrą, yra kompiuterio programinės įrangos atnaujinimas. Svarbu pabrėžti, kad būtent atlikus atnaujinimus, bus galima išvengti, kibernetinių virusų, kenkėjiškų programų, tad tokiu būdu bus užkertamas kelias saugumo  pažeidimams.",
      "section5_overload_body": "Reguliariai valykite jau nebereikalingus failus - būtent taip skamba dar vienas patarimas, kurio verta paisyti, jeigu norite, kad jūsų kompiuteris tarnautų kuo ilgiau. Esame įpratę valyti savo namus - atsisakyti jau nereikalingų daiktų, tačiau nereikėtų pamiršti lygiai to paties padaryti ir su savo kompiuteriu. Taigi, reguliariai peržiūrėkite jame esančius failus ir jau nebenaudojamus pašalinkite.",
      "section5_title_clean_display": "Kodėl reikia valyti kompiuterio monitorių?",
      "section5_title_cleaning?": "Ar verta valyti kompiuterį?",
      "section5_title_malware": "Kokie paprasti patarimai apsaugoti kompiuterį nuo kenkėjiškos programinės įrangos?",
      "section5_title_overload": "Kaip neapkrauti kompiuterio?",
      "section5_title_power_grid": "Ar pavojinga nešiojamą kompiuterį laikyti prijungtią prie elektros tinklo visą laiką?",
      "section5_title_ventilated_room": "Kodėl kompiuteris turi būti gerai vedinamoje patalpoje?",
      "section_about_us": "Jau daugiau nei 20 metų vilniečiams siūlome kokybiškas kompiuterių remonto ir naudotų kompiuterių bei jų komponentų pardavimo paslaugas. Per šį nemažą laikotarpį esame tvarkę itin sudėtingus kompiuterių komponentų ir programinės įrangos gedimus. Prireikus visuomet pasiūlome alternatyvas. Susisiekite ir padarysime viską, ką galime!",
      "section_about_us_title": "Apie UAB Kompservisas",
      "section_repair_services_call_us": "Skambinkite ir klauskite:",
      "section_repair_services_consultation": "Konsultacija perkant kompiuterį",
      "section_repair_services_data_backup": "Duomenų išsaugojimas",
      "section_repair_services_external_components": "Vidinių ir išorinių įrenginių instaliavimas",
      "section_repair_services_lcd_repair": "LCD/LED monitorių remontas",
      "section_repair_services_repair": "Stacionarių, nešiojamų kompiuterių remontas",
      "section_repair_services_sales": "Stacionarių, nešiojamų kompiuterių pardavimas",
      "section_repair_services_software_installation": "Programinės įrangos instaliavimas",
      "section_repair_services_title": "Kompiuterių remonto paslaugos",
      "section_repair_services_virus_removal": "Virusų paieška ir išvalymas"
    }
  },
  "supirkimas": {
    "section1_buyback_desktop_parts": "- stacionarių kompiuterių dalis",
    "section1_buyback_desktops": "- stacionarius kompiuterius (gali būti su įvairiais defektais)",
    "section1_buyback_laptop_parts": "- nešiojamų kompiuterių dalis",
    "section1_buyback_laptops": "- nešiojamus kompiuterius (gali būti su įvairiais defektais)",
    "section1_buyback_monitors": "- LCD monitorius (gali būti su įvairiais defektais)",
    "section1_buyback_no_older": "Superkame ne senesnius kaip <strong>5 metų:</strong>",
    "section1_title_buyback": "Supirkimas",
    "section2_buyback_large_quantities": "Dėl supirkimo dideliais kiekias prašome kreiptis el. paštu: <1>info@kompservisas.lt<1/>.",
    "section2_buyback_price": "Galutinė supirkimo kaina nustatoma apžiūrėjus prekę ir įvertinus jos techninę būklę. Su savimi būtinai turėti <strong>asmens tapatybę patvirtinantį dokumentą.</strong>",
    "section2_buyback_stolen_goods": "Vogtų daiktų arba daiktų parduodamų nepilnamečių asmenų <strong>NESUPERKAME</strong>."
  }
}

export default Resources;
